CREATE TABLE "tanah_kas" (
	"id" text PRIMARY KEY NOT NULL,
	"asal" text NOT NULL,
	"nomor_sertifikat" text NOT NULL,
	"luas_tanah" integer NOT NULL,
	"kelas_tanah" text NOT NULL,
	"milik_desa" integer,
	"milik_pemerintah" integer,
	"milik_provinsi" integer,
	"milik_kabupaten_atau_kota" integer,
	"milik_lainnya" integer,
	"tanah_sawah" integer,
	"tanah_tegal" integer,
	"tanah_kebun" integer,
	"tanah_tambak" integer,
	"tanah_kering" integer,
	"tanah_patok" integer,
	"tanah_tidak_patok" integer,
	"lokasi" text NOT NULL,
	"mutasi" text,
	"keterangan_tambahan" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
