CREATE TABLE "tanah" (
	"id" text PRIMARY KEY NOT NULL,
	"nama_pemilik" text NOT NULL,
	"total_luas" integer NOT NULL,
	"hak_milik" text,
	"hak_guna_bangunan" text,
	"hak_pakai" text,
	"hak_guna_usaha" text,
	"hak_pengelolaan" text,
	"hak_milik_adat" text,
	"hak_vi_milik_pribumi" text,
	"tanah_negara" integer,
	"perumahan" integer,
	"perdagangan_dan_jasa" integer,
	"perkantoran" integer,
	"industri" integer,
	"fasilitas_umum" integer,
	"sawah" integer,
	"tegalan" integer,
	"perkebunan" integer,
	"peternakan_perikanan" integer,
	"hutan_belukar" integer,
	"hutan_lebat" integer,
	"tanah_kosong" integer,
	"lain_lain" integer,
	"mutasi" integer,
	"keterangan_tambahan" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
